### ISSUE TITLE
Develop an application read/display the pedestals

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/xpedaq#11]
We discussed this a little bit and concurred that:
- this would be separate from the main DAQ program
- it would support the pedestal acquisition both through a single cluster (flight mode) and with the 8 clusters in parallel
- it would provide some minimal stat/visualization capability.

We still need to settle on what we would use for the visualization, as Qt does not provide anything out of the box.

**Comment by albertomanfreda** [comment]
At the moment the former pMainWindow class has been splitted in a base class pAcquisitionWindow and derived, specific subclasses for each application (i.e. xpedaqWindow, xpepedsWindow). However, the base class still holds a lot of code and functionalities specific of xpedaq which needs to be moved in the relevant subclass, before we can actually use it as a base class for xpepedsWindow.

**Comment by albertomanfreda** [comment]
We need a thread-safe way to pass the pDataBlock objects to the pedestal application as soon they are created in pDataCollector::run().
There is a nice example of something similar in the Qt documentation:
http://doc.qt.io/qt-4.8/qt-threads-mandelbrot-example.html

and judging by this example the best thing you can do is probably to simply 'emit' the pDataBlock (whether if by value or by const reference I am still not sure) in a signal like this:

emit dataBlockRead(pDataBlock dataBlock)

that will be asynchronously received by the main application. We need to use a [QMutex](http://doc.qt.io/qt-4.8/qmutex.html) to ensure that this operation is thread safe.
Since this is a **queued connection** (because it happens between different threads) the pDataBlock object will be implicitly copied by Qt, no matter how we pass it (see [this](http://stackoverflow.com/questions/18717816/does-emit-copy-its-arguments) discussion on stackoverflow) ). So we need to ensure that the copy of the pDataBlock object is made in the right way, i.e. that Qt knows how to copy a pDataObject correctly.

We can do that by using the Qt function qRegisterMetaType which (as stated [here](http://doc.qt.io/qt-4.8/qmetatype.html#qRegisterMetaType) ) works for 'any class or struct that has a public default constructor, a public copy constructor and a public destructor'. The conseqeunce is that the pDataBlock class must have them all.

[Here](http://www.embeddeduse.com/2013/06/29/copied-or-not-copied-arguments-signals-slots/) is an interesting lesson about what happens behind the stage when arguments are passed by signal-slot connections.

**Comment by lucabaldini** [comment]
Can we close this one? Alberto?

**Comment by albertomanfreda** [comment]
The application is in place. It has not been updated for a while, but we have specific issues for what we need to do, so I think we can close this one.
